#!/bin/sh

alias status="git status"
git config --global alias.lg "log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
alias log="git lg"
alias add="git add"
alias push="git push"
alias pull="git pull"
alias rebase="git rebase"
alias commit="git commit -v"
alias diff="git diff"
alias checkout="git checkout"
alias branch="git branch"
alias merge="git merge"
alias flow="git flow"
alias tag="git tag"
alias feature="flow feature"
alias hotfix="flow hotfix"
alias release="flow release"
alias stash="git stash"
alias remote="git remote"
alias clone="git clone"
alias fetch="git fetch"
