source $(dirname $0)/git-aliases.sh
source $(dirname $0)/docker.sh
source $(dirname $0)/ø.sh
source $(dirname $0)/boot2docker.sh
source $(dirname $0)/nvm.sh
source $(dirname $0)/rvm.sh
source $(dirname $0)/simple-server.sh
source $(dirname $0)/work.sh
source $(dirname $0)/fbr.sh
source $(dirname $0)/re.sh
source $(dirname $0)/vm.sh
source $(dirname $0)/generic.sh
source $(dirname $0)/todo.sh
source $(dirname $0)/fortune.sh
source $(dirname $0)/en_US.sh
