alias test='yarn test'
alias start='yarn start'
alias build='yarn run build'
alias publish='yarn publish'
alias version='npm version'
alias i='yarn add'
alias lint='yarn run lint'
alias reinstall='rm -rf node_modules && rm -f npm-debug.log && npm install'
